### ISSUE TITLE
Gatekeeper does not fail if the webhook job fails

### ISSUE THREAD

**Issue by yuriydzobak** [upsidr/merge-gatekeeper#36]
Hi,
I faced with an issue
The gatekeeper is checking webhook job correct only for status `Successful`
```
Total job count:     2
    jobs: ["atlantis/plan" "yaml: lint"]
  Completed job count: 2
    jobs: ["atlantis/plan" "yaml: lint"]
  Failed job count:    0
    jobs: []
```    
The gatekeeper doesn't verify if webhook job is fail and that isn't stopped after timeout. 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/70581130/183581789-8140cefa-651c-4cb6-9be8-b998dd496dd0.png">
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/70581130/183582583-72b06653-5539-4f7d-8c5a-73e775754bdf.png">

As you see only one GHA displayed
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/70581130/183582728-5ca00209-d65b-47ed-b15e-3fcaf6cb31ac.png">

**Comment by rytswd** [comment]
Hi @yuriydzobak, thanks for raising the issue! 👍

Merge Gatekeeper looks at the GitHub Action status, and is specifically looking for a state called `error` in the current implementation. How do you have your `atlantis/plan` job configured / triggered, and do you see some other status with it?

For further investigation, we may need to add an external flag for verbose logging, so that we can pinpoint what's happening with the actual job input. I believe the actual fix for this would be simply to catch other statuses, so that should be straightforward. We will look to see what we can do from our end, but if you can help fill in some details above, it would allow us to get a patch release for your specific use case quickly 🙏

**Comment by yuriydzobak** [comment]
Hi @rytswd 

> Hi @yuriydzobak, thanks for raising the issue! 👍
> 
> Merge Gatekeeper looks at the GitHub Action status, and is specifically looking for a state called `error` in the current implementation. How do you have your `atlantis/plan` job configured / triggered, and do you see some other status with it?

webhook configuration -> [link](https://www.runatlantis.io/docs/configuring-webhooks.html#github-github-enterprise)

> For further investigation, we may need to add an external flag for verbose logging, so that we can pinpoint what's happening with the actual job input. I believe the actual fix for this would be simply to catch other statuses, so that should be straightforward. We will look to see what we can do from our end, but if you can help fill in some details above, it would allow us to get a patch release for your specific use case quickly 🙏

If i understand correct it sends [this](https://github.com/runatlantis/atlantis/blob/584105ccc394a9ee856ccd3d7c374ed600179041/server/events/models/commit_status.go#L35) and you are validating [this one ](https://github.com/upsidr/merge-gatekeeper/blob/d6129ef212f3f9a9e542d384bb711cd7d68827a0/internal/validators/status/validator.go#L15)

**Comment by yuriydzobak** [comment]
I've reproduced the issue
if the status of commit is `failure` then gatekeeper doesn't see it 
If the status of commit is `error` then all works

doc: https://docs.github.com/en/rest/commits/statuses#create-a-commit-status
The state of the status. - Can be one of: `error, failure, pending, success`
gatekeeper doesn't have logic to check `failure`

**Comment by rytswd** [comment]
@yuriydzobak Thanks very much for further details!
I have created a PR for fixing this. We will look to get this merged in the coming days, and cut a new patch release right after 👍

**Comment by yuriydzobak** [comment]
I've checked from your branch and all works as expected
Thank you very much

**Comment by rytswd** [comment]
Thanks for testing! `v1.1.1` has been released with the above fix ☺️ 
We will update the relevant major and minor version tags (`v1` and `v1.1`) in the coming days as well.
