### ISSUE TITLE
Unable to detect jobs.

### ISSUE THREAD

**Issue by Marellasai** [upsidr/merge-gatekeeper#56]
Hello Guys, I have configured merge-gatekeeper as a workflow by following the doc, but when I do the PR to my repository merge-gatekeeper is getting triggered but it says 0 out of 0 jobs found. I need like if any of the other workflows in the repo fails that should stop the merge(as the merge-gatekeeper acts as a check). Please help.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/106055381/203623312-d581156e-d9c9-4062-864f-a6524e506db9.png">

**Comment by rytswd** [comment]
Hi @Marellasai ! The above description indicates that you are having the Merge Gatkeeper run against a commit ref that has no GitHub Actions / CI jobs associated. Merge Gatekeeper's main idea is to tie itself with a commit ref, and check its status via calling GitHub API. If GitHub API returns no associated job, it would show up with 0 for everything.

It would be difficult to debug further without the actual configurations for your CI suite (can be a mock) - would you be able to provide more?
